include "Library.dfy"

// //////////////////////////////////////////////////////////////////////////////

//
// lemma  SetNothing<T>(a : set<T>, b : set<T>)
//   requires (a - b) == {}
//    ensures  a <= b
// {}

lemma SetLtGtEq<T>(a : set<T>, b : set<T>)
  requires a >= b
  requires a <= b
   ensures a == b
{}

lemma  SetMinus0<T>(a : set<T>, b : set<T>)
  requires (a - b) == {}
   ensures  a <= b
{
  forall x <- a ensures (x in b) //by
   {
      assert x in a;           //all generated by copilot...
      assert (a - b) == {};
      assert not(x in (a - b));
      assert x in b;
  }
}


lemma  SetMinus3<T>(a : set<T>, b : set<T>, c : set<T>)
 //a is split between b !! c
  requires a - b == c
  requires a >= b
  requires a >= c
   ensures a - c == b
   ensures b !! c
   ensures a == b + c
{}


lemma  SetMinus4<T>(a : set<T>, b : set<T>, c : set<T>, d : set<T>)
  requires a == c
  requires b == d
  ensures (a - b) == (c - d)
{}

lemma  SetMinus6<T>(a : set<T>, b : set<T>, c : set<T>, d : set<T>, e : set<T>, f : set<T>)
  requires a == d
  requires b == e
  requires c == f
  ensures (a - b - c) == (d - e - f)
{}

lemma Set3Eq3<T>(a : set<T>, b : set<T>, c : set<T>, d : set<T>, e : set<T>, f : set<T>)
  requires a == d
  requires b == e
  requires c == f
  ensures  (a+b+c) == (d+e+f)
{}





lemma SetPlus1<T>(o : T, left : set<T>, right : set<T>)
// (left == right) ==> ({o}+left == {o}+right)
 requires left == right
  ensures {o} + left == {o} + right
{}


lemma SetGTEQ3<T>(a : set<T>, a0 : set<T>, a1 : set<T>, a2 : set<T>, b : set<T>, b0 : set<T>, b1 : set<T>, b2 : set<T>)
  requires a == a0 + a1 + a2
  requires b == b0 + b1 + b2
  requires a0 !! a1 !! a2
  requires b0 !! b1 !! b2
  requires (a0 >= b0)
  requires (a1 >= b1)
  requires (a2 >= b2)
   ensures a >= b
{}

lemma SetGTEQ2<T>(a : set<T>, a0 : set<T>, a1 : set<T>, b : set<T>, b0 : set<T>, b1 : set<T>)
  requires a == a0 + a1
  requires b == b0 + b1
  requires a0 !! a1
  requires b0 !! b1
  requires (a0 >= b0)
  requires (a1 >= b1)
   ensures a >= b
{}




lemma Set_ONE_OR_TOTHER<T>(a : T, b : set<T>, c : set<T>)
requires a !in b
requires c ==  b + {a}

ensures a in c
ensures {a} <= c
ensures b <= c

ensures forall y <- c :: (y == a)  ==> (y !in b)
ensures forall y <- c :: (y == a) <==  (y !in b)
ensures forall y <- c :: (y == a) <==> (y !in b)
ensures forall y <- c :: (y == a) <==  (y !in b)

ensures forall y <- c :: (y != a)  ==> (y in b)
ensures forall y <- c :: (y != a) <==  (y in b)
ensures forall y <- c :: (y != a) <==> (y in b)
ensures forall y <- c :: (y != a) <==  (y in b)

ensures forall y <- c :: (y == a)  !=  (y in b)
{}
